Update build-wheel.yml

diff --git a/.github/workflows/build-wheel.yml b/.github/workflows/build-wheel.yml
--- a/.github/workflows/build-wheel.yml
+++ b/.github/workflows/build-wheel.yml
@@ -106,18 +106,18 @@ jobs:
           git submodule update --init --recursive
 
       # 独立swap文件，避开系统占用的 /swapfile
-      - name: Enable swap memory
-        run: |
-          SWAP_PATH=/home/runner/swap8g
-          rm -f ${SWAP_PATH}
-          if ! sudo fallocate -l 8G ${SWAP_PATH}; then
-            echo "fallocate failed, using dd fallback"
-            sudo dd if=/dev/zero of=${SWAP_PATH} bs=1G count=8 status=none
-          fi
-          sudo chmod 600 ${SWAP_PATH}
-          sudo mkswap ${SWAP_PATH}
-          sudo swapon ${SWAP_PATH}
-          swapon --show
+      #- name: Enable swap memory
+      #  run: |
+      #    SWAP_PATH=/home/runner/swap8g
+      #    rm -f ${SWAP_PATH}
+      #    if ! sudo fallocate -l 8G ${SWAP_PATH}; then
+      #      echo "fallocate failed, using dd fallback"
+      #      sudo dd if=/dev/zero of=${SWAP_PATH} bs=1G count=8 status=none
+      #    fi
+      #    sudo chmod 600 ${SWAP_PATH}
+      #    sudo mkswap ${SWAP_PATH}
+     #     sudo swapon ${SWAP_PATH}
+     #     swapon --show
      # - name: Free disk space
      #   run: |
      #     df -h
